export var menus = [['https://www.choicehotels.com/michigan/utica/comfort-inn-hotels/mi413?source=gyxt', []]
,['http://www.konagrill.com/locations/troy-mi', ['https://www.konagrill.com/menu', 'http://www.konagrill.com/menu/kitchen', 'http://www.konagrill.com/menu/power+lunch', 'http://www.konagrill.com/menu/cocktails', 'http://www.konagrill.com/menu/kids', 'http://www.konagrill.com/menu/family+meals', 'http://www.konagrill.com/menu/happy+hour']]
,['https://www.texasroadhouse.com/locations/michigan/sterling-heights', ['https://www.texasroadhouse.com/menu/food/hand-cut-steaks-ribs', 'https://www.texasroadhouse.com/texas-roadhouse-master-menu.pdf']]
,['http://www.gcfb.net/location/troy-michigan', ['http://www.gcfb.net/wp-content/uploads/2019/04/MothersDay_Menu_T56.pdf']]
,['http://www.monjinlau.com/', []]
,['http://www.beercos.com/', ['https://www.carrabbas.com/menu', 'https://www.carrabbas.com/menu/nutrition/']]
,['https://www.carrabbas.com/', ['https://www.carrabbas.com/menu', 'https://www.carrabbas.com/menu/nutrition/']]
,['https://locations.maggianos.com/michigan/troy/2089-west-big-beaver-rd/?utm_source=google&utm_medium=organic&utm_campaign=localmaps', ['https://locations.maggianos.com/michigan/troy/private-dining/', 'https://locations.maggianos.com/michigan/troy/2089-west-big-beaver-rd/main-menu/', 'https://locations.maggianos.com/michigan/troy/2089-west-big-beaver-rd/private-dining/']]
,['http://www.ikesrestaurant.com/', ['http://www.ikesrestaurant.com/our-menu/']]
,['https://www.bahamabreeze.com/locations/mi/troy/detroit-troy/3026?cmpid=br:bb_ag:ie_ch:loc_ca:BBGMB_dt:20190131_sn:gmb_gt:troy-mi-3026_pl:locurl_rd:1014', ['https://www.bahamabreeze.com/menu-listing/happy-hour', 'https://www.bahamabreeze.com/private-dining/home', 'https://www.bahamabreeze.com/menu-listing/family-style-serves-4/caribbean-bundles', 'https://www.bahamabreeze.com/menu-listing/food', 'https://www.bahamabreeze.com/menu-listing/family-style-serves-4/family-entrees']]
,['https://www.olivegarden.com/locations/mi/sterling-heights/sterling-heights-lakeside-circle/1083?cmpid=br:og_ag:ie_ch:loc_ca:OGGMB_dt:20190131_sn:gmb_gt:sterling-heights-mi-1083_pl:locurl_rd:1052', ['https://www.olivegarden.com/menu-listing/pronto-lunch', 'https://www.olivegarden.com/menu-listing/alcoholic-beverages', 'https://www.olivegarden.com/menu-listing/beverages', 'https://www.olivegarden.com/menu-listing', 'https://www.olivegarden.com/menu-listing/dinner', 'https://www.olivegarden.com/menu-listing/wines', 'https://www.olivegarden.com/menu-listing/desserts']]
,['http://andiamoitalia.com/', ['https://andiamoitalia.com/wp-content/uploads/2020/03/andiamo-family-style-at-home-menu.pdf', 'https://andiamoitalia.com/wp-content/uploads/2020/03/andiamo-grab-go-menu.pdf']]
,['https://www.buffalowildwings.com/en/locations/detail/3690/?utm_source=google&utm_medium=organic&utm_campaign=rio', []]
,['http://www.chbfd.com/', []]
,['http://www.picanos.com/', []]
,['http://www.redoxtavern.com/', []]
,['http://www.fivestarlanes.com/', []]
,['http://www.sterlinginn.com/', []]
,['https://www.redlobster.com/locations/list/mi/rochester-hills/2825-s-rochester-road', []]
,['http://www.ckdiggs.com/', []]];